### ISSUE TITLE
Java API support

### ISSUE THREAD

**Issue by ffly1985** [rapidsai/rmm#115]
Any Java Surpport in plan?

**Comment by jlowe** [comment]
There are some Java bindings to RMM that are currently in the cudf repo.  See [Rmm.java](https://github.com/rapidsai/cudf/blob/branch-0.9/java/src/main/java/ai/rapids/cudf/Rmm.java) and [RmmJni.cpp](https://github.com/rapidsai/cudf/blob/branch-0.9/java/src/main/native/src/RmmJni.cpp).

Looks like those bindings should move to this repo and published to a Maven repository so cudf can depend on them rather than include them directly.  This would mirror the dependency of the cudf native code, which used to pull in RMM via a submodule and now expects it to be available as part of the build environment.

**Comment by anfeng** [comment]
You could try out cudf maven artifacts from central repo. 
https://search.maven.org/classic/#search%7Cga%7C1%7Ccudf

We support cuDF 9.2/10, Ubuntu or RHEL/CentOS.

**Comment by harrism** [comment]
@jlowe any interest from your team in contributing this?

**Comment by jlowe** [comment]
From a technical standpoint, definitely something we could do as it's already been done in cudf as I mentioned before. I'll defer to @sameerz to see if the team should start publishing and maintaining jar artifacts for RMM separate from what's already been done in the cudf JNI bindings.

It would be good to understand the use-cases for RMM JNI bindings that cannot be solved by using the existing bindings in the cudf jar to help prioritize the effort.

**Comment by harrism** [comment]
> It would be good to understand the use-cases for RMM JNI bindings that cannot be solved by using the existing bindings in the cudf jar to help prioritize the effort.

Another option is to simply close this issue.

But if Java is anything like C++, I would be pretty annoyed to have to install and use another library just to get the functionality of this one.

**Comment by sameerz** [comment]
Would love to hear if there are any use cases for supporting a Java API for RMM.  Otherwise we do not have immediate plans to support this.

**Comment by harrism** [comment]
We can put this on the backlog until we get a more concrete request.

**Comment by harrism** [comment]
@ffly1985 if you have a concrete use case, please reopen this issue and provide some details. But I'm closing this for now due to inactivity.
