### ISSUE TITLE
[QST] Mixing MemoryResource, and Prefetching

### ISSUE THREAD

**Issue by HanGuo97** [rapidsai/rmm#1322]
Hello! Firstly, I want to express my gratitude for this incredible library. I spent a significant amount of time searching for a tool like this, and it's exactly what I was looking for.

I have a question as a beginner and I would appreciate your help. I primarily use this library through its PyTorch frontend, and I'm curious if (and how) I can accomplish the following:

1. Is it possible to do prefetching or provide hints for `rmm.mr.ManagedMemoryResource`, or must I rely solely on unified memory's mechanism?
2. Can I simultaneously use `CudaMemoryResource` and `ManagedMemoryResource`, and designate certain data as pageable and others as non-pageable?

Thanks in advance for your help!

**Comment by vyasr** [comment]
Apologies for the slow response here. These questions have different answers depending on whether you are using rmm directly or not. I'll start with direct rmm usage, then discuss the pytorch case.

1. I haven't tried it, but in theory you should be able to leverage cuda-python to manage prefetching/hints for rmm allocations. An rmm memory allocation produces an `rmm.DeviceBuffer`, and you should be able to pass that object's `.ptr` directly to `cuda.cudart.cudaMemAdvise` to provide hints or `cuda.cudart.cudaMemPrefetchAsync` to prefetch manually.
2. You can certainly use multiple resources. Every memory resource defined in `rmm.mr` has an `allocate` function, so you can choose to perform allocations using one resource or the other depending on your needs, e.g. `mr_cuda = rmm.mr.CudaMemoryResource(); alloc1 = mr_cuda.allocate(100)`.

However if you are using the pytorch allocator and setting that to pytorch then I'm not sure there is any way you can do this, and it probably wouldn't even make sense for you to do it yourself. You would need PyTorch to manage this since you don't know how it wants to use a particular allocation relative to other allocations. @shwina may have more thoughts on the best way to do this.

**Comment by HanGuo97** [comment]
This is very clear, thanks both for the detailed explanations!
