### ISSUE TITLE
[FEA] Add release() function to pool resources

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/rmm#145]
**Is your feature request related to a problem? Please describe.**
Calling `rmmFinalize` should deallocate the memory pool in any of the pool resources. Currently the only way to free a pool is when the pool resource is destroyed at the end of the application. 

**Describe the solution you'd like**
The pool resources need `release` methods added to free their memory pools. For example, see [`std::pmr::synchronized_pool::release()`](https://en.cppreference.com/w/cpp/memory/synchronized_pool_resource/release).

**Additional context**
When `rmmFinalize` is invoked, how do we know what resources to call `release` on? `release` is not a member of the `device_memory_resource` base class, so it's not possible to call `get_default_resource()->release()`. Do we just always call `pool_resource()->release()` and `managed_pool_resource()->release()`? But that will end up constructing those resources only to then release them.

**Comment by harrism** [comment]
I guess we follow the same logic as in rmmInitialize(). Assuming the options haven't changed, only pools that were constructed will be released.

However this just creates a different problem. Since the pools are singletons, calling rmmInitialize() again with different options will not call the MR constructors a second time. So for example it will not be possible to resize the pool.

One option is to make pool resize a public method of the pool resources.  Another option is to somehow stop using singletons for MRs.

**Comment by ayushdg** [comment]
I'm not too familiar with rmm internal for the concepts of singletons, but how would it impact the situation where I want to reinitialize rmm (without pool mode) after finalizing rmm which was initialized with the pool allocator?

**Comment by harrism** [comment]
@ayushdg that's exactly what I'm talking about. Currently the way it is implemented there is no reliably way to re-initialize RMM with the same type of memory but different arguments (e.g. pool size).

**Comment by jrhemstad** [comment]
> @ayushdg that's exactly what I'm talking about. Currently the way it is implemented there is no reliably way to re-initialize RMM with the same type of memory but different arguments (e.g. pool size).

Since it isn't possible to initialize RMM more than once from Python using the `set_allocator` API, I assumed this wasn't a necessary feature.

**Comment by ayushdg** [comment]
Libraries like XGBoost don't use RMM. So workflows which do ETL (using rmm pool mode) need to move the data temporarily to the host to free up the memory on the device before training their model with XGBoost.

The `set_allocator` api does not allow users to initialize RMM more than once so I usually resort to using the `rmm` api itself or using the non public `cudf._set_rmm_config` to achieve this.

**Comment by jrhemstad** [comment]
> Libraries like XGBoost don't use RMM. So workflows which do ETL (using rmm pool mode) need to move the data temporarily to the host, free up the memory on the device (with finalize) and then train their model with XGBoost.
> 
> The `set_allocator` api does not allow users to initialize RMM more than once so I usually resort to using the `rmm` api itself or using the non public `cudf._set_rmm_config` to achieve this.

Right, so I'd expect the workflow to look like this:
```
rmmInitialize();
// do ETL
rmmFinalize();
// do XGBoost
```

Where's the need to initialize RMM more than once?

**Comment by ayushdg** [comment]
Currently `rmmFinalize();` does not clear the the pool memory, so XGBoost does not have enough memory available to train the model.

Speaking to the specific point of initializing RMM more than once: 
Currently the mortgage workflow looks like this:

```
rmmInitialize(pool=True);
//do ETL
// Move data to host
rmmFinalize();
rmmInitialize(pool=False);
//cudf read host data (without pool mode)
//Concat some df's to create the training set
// Pass GPU Dmatrix to XGBoost.
```

It might be possible to use the GPU for XGBoost training by providing a host dmatrix and letting XGBoost handle moving the data to the gpu. But I presume the existing mortgage workflow does it this particular way because it might be faster? (It's more of a hypothesis than a claim)

**Comment by harrism** [comment]
This feature request is superseded by #146, an alternative fix.
