### ISSUE TITLE
[QST] RMM Allocation from another python module

### ISSUE THREAD

**Issue by guilhermehartmann** [rapidsai/rmm#231]
Is there a standard way to use the RMM allocation from another C++ library wrapped in cython? The idea is to interface a custom multi-gpu sparse matrix library with the standard cuDF or cupy data structures.

**Comment by kkraus14** [comment]
@guilhermehartmann I've transferred the issue to the RMM repo. We export the Cython headers so you can use our Cython functions to work with `device_buffer` objects: https://github.com/rapidsai/rmm/blob/branch-0.12/python/rmm/_lib/device_buffer.pxd or can use raw pointers via the corresponding `alloc` / `free` functions.

**Comment by guilhermehartmann** [comment]
Thanks Keith, I will be taking a look. I was mostly thinking about the behaviour of rmm where all of the GPU is pre-allocated and managed internally. How is the state shared between different C++ libraries using rmm?

**Comment by kkraus14** [comment]
@guilhermehartmann if they're all of the libraries are in a single process then everything just works because there's a single context and instance of the RMM memory pool being shared. If you have multiple processes that isn't supported, but you could in theory build a shim layer to a single process that does all of the memory management, then shares that memory to other processes via CUDA IPC. This would be extremely non-trivial to implement.

**Comment by harrism** [comment]
Closing. Please comment if there is still an issue here.

**Comment by guilhermehartmann** [comment]
Just a quick update, I had luck invoking cudf make column directly from my shared library. Any problems with this approach ?

**Comment by kkraus14** [comment]
Not at all, sounds great!
