### ISSUE TITLE
[FEA] `logging_resource_adaptor` should support java requirements

### ISSUE THREAD

**Issue by rongou** [rapidsai/rmm#355]
The `logging_resource_adaptor` is currently duplicated in the cudf JNI binding (see
https://github.com/rapidsai/cudf/blob/2b2ba1847e1bc2debcacb0cb1a2140c86fc52868/java/src/main/native/src/RmmJni.cpp#L371). @revans2 mentioned a couple of reasons that this happened (https://github.com/rapidsai/cudf/pull/4816#issuecomment-619308420). Should there be a single version that supports both c++ and java requirements?

**Comment by harrism** [comment]
@rongou can you please document the requirements in this issue to save time / prevent confusion?

**Comment by rongou** [comment]
Two requirements from @revans2's comments:

The first is that the header-only library, spdlog, is not included with rmm, so as soon as you try to even include the header file with logging_resource_adaptor in it you need to also pull in spdlog. For rmm they included the library as part of the repo, but here in cudf it is not available, and it is not shipped with rmm so it was simpler to write my own than it was to try and pull in a new dependency.

The second is that logging_resource_adaport only supports writing to a file, and we needed to support stdout and stderr because it fits better with spark and how it does logging. So if I wanted to use it I would also have to make changes to rmm to support stdout and stderr. They would not be big changes, but all of it together was more then I wanted to worry about.

**Comment by revans2** [comment]
I think there is a difference between a requirement and a barrier to entry. Being able to use logging_resource_adaptor with stdout and stderr is a requirement if Spark is going to use it. The lack of spdlog header files is a barrier to entry for using the logging_resource_adaptor at all. I could have made it work. RMM chose to check the library into their repo so I assumed that there wasn't a simple conda package I could install.  Even then a new C++ dependency is a difficult thing to push through in cudf. Instead of checking in the source code for a full logging library, I decided to just write the code I needed which ended up being much smaller.  I should have filed something here to describe our situation, but I had found an acceptable solution and I had a lot of other things to work on.

Thanks @rongou for filing this, but I want to make sure that @harrism knows that we have a working solution right now, but the logging_resource_adaptor is very difficult to use outside of rmm source code so if you do want others to use it you might want to look at reducing the barrier to entry.  If you do reduce that barrier having support for logging to stdout and stderr would be a requirement for Spark to use this.

**Comment by rongou** [comment]
The reason I filed this was that I was trying to log the thread id in PTDS mode, but my changes to the RMM logging_resource_adaptor had no effect. It took a while to figure out there is another definition of it in the JNI code.

This is certainly not urgent, but having duplicate code just seems bad.

**Comment by harrism** [comment]
We do use the logging resource adaptor from Python, FWIW. Please keep in mind that adding this was a quick fix because we needed logging for some urgent investigations. We can revisit.

Supporting arbitrary streams and not just files is indeed a good suggestion.

I would have preferred a smaller, header-only library, but there were tradeoffs. See https://github.com/rapidsai/rmm/issues/295

I would have also preferred a submodule, I can't remember why @jrhemstad chose to vendor it directly. We could also make it a cmake module, like we do for gtest.

We are going to have to reconsider how we do it when we move RMM to be a header-only library...

**Comment by jrhemstad** [comment]
> Supporting arbitrary streams and not just files is indeed a good suggestion.

Agreed, this is relatively easy to do since spdlog already supports this.

I don't understand the consternation about spdlog. 

> I would have preferred a smaller, header-only library, but there were tradeoffs.

`spdlog` _is_ header only.

> I would have also preferred a submodule, I can't remember why @jrhemstad chose to vendor it directly.

This didn't come up in review. Likewise, it wouldn't solve any problems here. It would just make it _more_ difficult because you'd have to remember to init submodules when you clone RMM. 

> The first is that the header-only library, spdlog, is not included with rmm

What do you mean it isn't included? https://github.com/rapidsai/rmm/tree/branch-0.14/thirdparty/spdlog

> the logging_resource_adaptor is very difficult to use outside of rmm source code so if you do want others to use it you might want to look at reducing the barrier to entry.

I'm very confused about why it is so difficult. A vendored, header-only library is the lowest user effort solution I can possibly think of.

**Comment by revans2** [comment]
> > The first is that the header-only library, spdlog, is not included with rmm
> 
> What do you mean it isn't included? https://github.com/rapidsai/rmm/tree/branch-0.14/thirdparty/spdlog

Sorry, I should have said that it is not included with the `librmm` conda package.  So if I want to create an instance of a `logging_resource_adaptor` in cudf I have to find a way to get access to the spdlog headers.

> > the logging_resource_adaptor is very difficult to use outside of rmm source code so if you do want others to use it you might want to look at reducing the barrier to entry.
> 
> I'm very confused about why it is so difficult. A vendored, header-only library is the lowest user effort solution I can possibly think of.

Yes, I agree that it is a low barrier to entry for a C++ dependency, but all C++ dependencies provide a decently high barrier to entry. Enough that when I wanted to use the adaptor it was simpler to write my own 120 line class than to try and find a way to pull in spdlog into cudf.  I am not a C++ expert so I could be missing something.

**Comment by jrhemstad** [comment]
> Sorry, I should have said that it is not included with the librmm conda package

Ah, okay, that's a solvable problem. I thought the `thirdparty` directory was packaged as part of the conda package. I didn't realize Java relied on the conda packages.

**Comment by revans2** [comment]
Just doing what is simplest and fastest.  Didn't want to wait and I would have forgotten about it without the help from @rongou
