### ISSUE TITLE
[FEA] Add CMake export target.

### ISSUE THREAD

**Issue by trivialfis** [rapidsai/rmm#455]
**Is your feature request related to a problem? Please describe.**

I wish I could use RMM with normal CMake `find_package` facility.  As RMM is a C++ library,  I think it's a reasonable expectation that other C++ libraries can use CMake `find_package` to add RMM as a dependency.

**Describe the solution you'd like**

Use CMake export facility: https://cmake.org/cmake/help/latest/command/install.html#export

**Describe alternatives you've considered**

Use conda to find C++ header with CMake script: https://github.com/dmlc/xgboost/pull/5873#discussion_r463934189

**Comment by trivialfis** [comment]
cc @hcho3

**Comment by hcho3** [comment]
> RMM now a header only C++ library ...

Not yet. See #408. The CNMeM allocator needs to be removed first (#407).

**Comment by trivialfis** [comment]
@hcho3  Thanks.  Changed "header only C++ library" into "C++ library", the remaining is still valid.

**Comment by germasch** [comment]
FWIW, I happen to be working on this right now.

**Comment by harrism** [comment]
Excellent, I've taken the liberty of assigning you, @germash.

Note that we are going to be entering our burndown phase of the 0.15 release tomorrow, so please switch your PR to target the 0.16 branch when it becomes available. Here is the schedule: https://docs.rapids.ai/maintainers

**Comment by germasch** [comment]
Do you mean the current PR (#461)? That's pretty harmless (famous last words...)

In fact I could submit the PR that actually adds a `rmm-config.cmake` during the burndown phase (probably tomorrow). I'd also characterize it as relatively harmless in terms of potential of causing breakage, since it just adds a few config files to what gets installed. It would, however, not address the issue #393 of how to deal with other dependencies like spdlog. That makes it imperfect, but not worse than the status quo.

Specifically, I have it at a point where I can do `find_package(rmm)` in a downstream project, and that'll work, as long as one isn't using the logging resource without making spdlog available (or similarly, use the rmm thrust allocator without having thrust available, though that's likely not a problem in practice since thrust is bundled with cuda). If a downstream project wanted to use the logging, it would have to make spdlog available itself.

In any case, I think there's a good point to be made that one shouldn't merge a known-incomplete solution in a rush, and in any case, it's you guys' call.

**Comment by harrism** [comment]
When I wrote that I didn't realize you had opened a PR already.  We should be able to get #461 into 0.15. However our general rule for burndown is "no new PRs", so really should get them in before we start burning down.

**Comment by germasch** [comment]
Sorry for the confusion. #461 is just cleanup, prepping for the real one. I do have the real one almost ready, but it still needs some touching up.

**Comment by germasch** [comment]
This issue should now be resolved by #580.

**Comment by harrism** [comment]
Fixed by #580. @trivialfis please reopen if you find it is not.
