### ISSUE TITLE
[BUG] Initializing pool_memory_resource with 90% of GPU memory as initial size results in OOM

### ISSUE THREAD

**Issue by jlowe** [rapidsai/rmm#471]
**Describe the bug**
Trying to initialize `pool_memory_resource` with 90% of the GPU memory as the initial pool size and an unspecified maximum size fails with an OOM.  This used to work without an OOM.

**Steps/Code to reproduce bug**
On a 16GB GPU, try calling `pool_memory_resource` backed by a normal CUDA memory resource and with parameter initial_pool_size = 15250961203.  Instead of allocating the specified initial size (which would have succeeded) it ends up trying to allocate 16945512448 instead which fails.

**Expected behavior**
A clear and concise description of what you expected to happen.  Using `git bisect` it appears commit ae3a1fd531723c7aabda29858dbbf208b8ca6450 is where the behavior changed.

**Comment by jrhemstad** [comment]
So the problem is that when `pool_memory_resource` is constructed it attempts to allocate from the upstream to allocate the initial pool. It does this by calling the `block_from_upstream` function here: https://github.com/rapidsai/rmm/blob/9ae2966a6ff3a462704d78ece54d542ffe43caf1/include/rmm/mr/device/pool_memory_resource.hpp#L141

There are two problems here. The first is that `block_from_upstream` assumes the pool needs to grow, so it ends up allocating `initial_pool_size + (max_pool_size - current_pool_size)/2)` as seen here: https://github.com/rapidsai/rmm/blob/9ae2966a6ff3a462704d78ece54d542ffe43caf1/include/rmm/mr/device/pool_memory_resource.hpp#L242-L254

Which is incorrect because it should just allocate `initial_pool_size`. What's more, at this point, `current_pool_size` is zero, so it ends up trying to allocate `initial_pool_size + max_pool_size/2`. 

I'll fix by moving the `size_to_grow` logic outside of `block_from_upstream`.

**Comment by harrism** [comment]
I must have just broken this. I can fix Monday.

**Comment by rongou** [comment]
I have a quick fix following @jrhemstad's suggestion. Sending you a PR.
