### ISSUE TITLE
[QST] Why device_uvector has no copy assignment with stream arguments?

### ISSUE THREAD

**Issue by wkjung** [rapidsai/rmm#487]
**What is your question?**
Hi.

In `device_uvector.hpp`, copy ctor, default ctor, and copy assignment operator are deleted. Among them, copy ctor is overloaded (if wrong, correct me) by one with a stream argument (and device resource). But why the copy assignment operator has no corresponding function, and just deleted? Is it intended?

**Comment by jrhemstad** [comment]
Due to the inherent danger of stream ordered memory allocation, we made the decision to require all operations on `device_uvector` that incur a copy or allocation to require an explicit stream argument. 

The copy assignment operator is purposefully deleted because it is not possible to pass a stream argument to a `operator=`. This is also why the default copy constructor is deleted and the only option is an overload that requires a stream.

**Comment by wkjung** [comment]
I see. thanks.
