### ISSUE TITLE
[BUG] Initializing pool allocator with managed memory doesn't use initial_pool_size

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/rmm#531]
**Describe the bug**
When using `rmm.reinitialize` with the pool allocator and managed memory enabled, I don't see any GPU memory used despite the `initial_pool_size` value. 

**Steps/Code to reproduce bug**
```
rmm.reinitialize(pool_allocator=True, managed_memory=True, initial_pool_size=10000000000)

!nvidia-smi

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     25276      C   ...iconda3/envs/rapids-16-aug28/bin/python   139MiB |
+-----------------------------------------------------------------------------+

```

**Expected behavior**
In the case of pool allocator without managed memory, the gpu memory usage corresponds to the pool size provided.

```
rmm.reinitialize(pool_allocator=True, managed_memory=False, initial_pool_size=10000000000)

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     25276      C   ...iconda3/envs/rapids-16-aug28/bin/python  9677MiB |
+-----------------------------------------------------------------------------+
```

**Environment details (please complete the following information):**
 - Method of RMM install: conda 0.16 nightly from Aug28
```
 "date": "2020-08-27T17:35:49-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "d8d48b2ea8755c82838cfa818e7217f262dcb04d",
 "version": "0.16.0a+275.gd8d48b2"
```

**Comment by jrhemstad** [comment]
Managed memory is a form of virtual memory, so you won't see any GPU memory used until that memory is actually paged to the GPU by touching/using the memory.

**Comment by ayushdg** [comment]
Thanks for clarifying. 
I lack some knowledge about this topic, but what impact would the `initial_pool_size` and `maximum_pool_size` parameter have when I'm using a managed pool allocator? 

Does setting the `initial_pool_size` in this scenario still mean that other applications (not using rmm) will not be able to touch this memory even though it's not paged to the GPU?
Does the `maximum_pool_size` parameter mean that memory allocations beyond that limit will be handled by using host memory and paging into the Gpu when required?

**Comment by jrhemstad** [comment]
@ayushdg There is no difference in behavior of `initial_pool_size` and `maximum_pool_size` between using managed vs. non-managed memory.

`initial_pool_size` controls the size of the initial pool. In the case of managed memory, it will allocate a block of memory of size `initial_pool_size` of managed memory. Because it is managed memory, it doesn't actually consume GPU memory until it is paged or prefetched to the GPU. For more info about managed memory, I suggest taking a look at: https://developer.nvidia.com/blog/unified-memory-cuda-beginners/

`maximum_pool_size` controls the maximum size of the pool. If the `sum(allocations) - sum(deallocations)` ever exceeds `maximum_pool_size`, then an exception will be thrown.
