### ISSUE TITLE
[FEA] Refactor device/runtime APIs in `rmm._cuda.gpu`

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/rmm#574]
**Is your feature request related to a problem? Please describe.**

Currently `rmm._cuda.gpu` contains both device and runtime APIs. Based on discussion ( https://github.com/rapidsai/cudf/pull/4943#pullrequestreview-395881420 ), it would be good to refactor these.

**Describe the solution you'd like**

Ideally these would be refactored into 2 modules so that users could pull APIs from either one as needed.

**Describe alternatives you've considered**

Suggestions welcome 🙂

**Additional context**

NA

**Comment by jakirkham** [comment]
cc @galipremsagar

**Comment by harrism** [comment]
> Currently rmm._cuda.gpu contains both device and runtime APIs. 

Do you mean (CUDA) *driver* and runtime APIs?

**Comment by harrism** [comment]
@jakirkham @kkraus14  still relevant?

**Comment by kkraus14** [comment]
Yes but low priority.

**Comment by vyasr** [comment]
I'm going to close this as wontfix. Since this issue was originally created, the advent of cuda-python means that users shouldn't be getting this functionality from rmm anyway, and rmm's implementations have been stripped down thanks to calling cuda-python APIs. At this point `rmm_cuda.gpu` is a fairly small, internal-only, largely static module. We can reconsider if it needs to expand or move in any way in the future.
