### ISSUE TITLE
[FEA] Add member function for device_uvector and device_scalar to query the associated stream

### ISSUE THREAD

**Issue by fkallen** [rapidsai/rmm#885]
`device_buffer` has a function to query the stream of the last memory operation.
```
/**
   * @brief Returns stream most recently specified for allocation/deallocation
   */
  [[nodiscard]] cuda_stream_view stream() const noexcept { return _stream; }
```

It would be nice to have a similar function for `device_uvector`. This can help debugging, for example asserting that the stream has the expected value.

**Comment by harrism** [comment]
Should even device_buffer have a way to query the stream it stores?  In an ideal world, `device_buffer` would not store a stream. All of its methods require passing a stream (Except the destructor). The only reason it needs to store the stream is because destructors can't take parameters, and we need these RAII classes to use stream-ordered memory resources for deallocation.

My concern is that the stream could be destroyed without the object knowing, and then deallocating on the stream is UB.

`device_uvector` and `device_scalar` `stream()` query functions just pass through to `_storage.stream()`. Adding these means we also have to add `set_stream()` methods to these classes, like `device_buffer` (so that if the stream is deleted, and the owner knows it, they can set the stream to something different.)

I guess we have no choice but to add these for completeness.
